#!/usr/bin/env perl
use Mojolicious::Lite;

app->config(
    hypnotoad => {
        listen => ['http://*:80'],
        workers => 32,
        clients => 1000
    }
    );

get '/' => sub {
  my $c = shift;
  $c->render(text => 'true');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
Welcome to the Mojolicious real-time web framework!

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
