#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::JSON qw(encode_json);
use Mojo::Redis2;

app->config(
    hypnotoad => {
        listen => ['http://*:8000'],
        workers => 12,
    }
    );

my $redis = Mojo::Redis2->new(url => 'redis://192.168.32.98:6379/')->protocol_class('Protocol::Redis::XS');

post '/open/sms/send' => sub {
  my $c = shift;

  my $post_data = $c->req->json;

  my $send_num = $post_data->{'sourceAddr'};
  my $receive_num = $post_data->{'destAddr'};
  my $msg = $post_data->{'message'};
  # my $res_id = $uuid_gen->create_str;
  my $bytes = encode_json {mobiles => $receive_num, serviceid => '10658524', content => $msg};

  $c->delay(
      sub {
          my ($delay) = @_;
          $redis->rpush('dsReqQueueName', $bytes, $delay->begin);
      },
      sub {
          my ($delay, $err, $message) = @_;
          $c->render(text => 'OK');
      },
      );
  # $c->render(json => {
  #     'Message ID' => "$res_id",
  #     'Message Sender' => "$send_num",
  #     'Message Receriver' => "$receive_num",
  #     'Message' => "$msg"
  #           });
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>
To learn more, you can browse through the documentation
<%= link_to 'here' => '/perldoc' %>.

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
